server:
  port: 8080

spring: 
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: SERVICE1
        uri: lb://SERVICE1
        predicates: 
        - Path=/test1/**
      - id: SERVICE2
        uri: lb://SERVICE2
        predicates: 
        - Path=/test2/**      
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8090/eureka